### ISSUE TITLE
Docker template has error

### ISSUE THREAD

**Issue by ivashog** [marcjulian/nestjs-prisma#5]
You docker-compose.yml file includes an official postgres:12 image that needs some environment variables (see Environment Variables chapter on [dockerhub Postgres page](https://hub.docker.com/_/postgres/))
Environments provided by nestjs-prisma schematics `nestjs-prisma/schematics/nestjs-prisma/templates/docker/.env`
is incorrect:
```env
POSTGRESQL_USER=prisma
POSTGRESQL_PASSWORD=topsecret
POSTGRES_DB=food

DATABASE_URL=postgresql://prisma:topsecret@postgresprisma:5432/food?schema=food&sslmode=prefer
```
must bee:
```env
POSTGRES_USER=prisma
POSTGRES_PASSWORD=topsecret
POSTGRES_DB=food

DATABASE_URL=postgresql://prisma:topsecret@postgresprisma:5432/food?schema=food&sslmode=prefer
```

Also prisma 0.2.7 support [dotenv-expand](https://github.com/motdotla/dotenv-expand) ([see docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema#accessing-environment-variables-from-the-schema)) which allows us to make the following improvement:
```env
POSTGRES_USER=prisma
POSTGRES_PASSWORD=topsecret
POSTGRES_DB=food

DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresprisma:5432/${POSTGRES_DB}?schema=food&sslmode=prefer
```

**Comment by marcjulian** [comment]
@ivashog thanks for pointing out the error and also the cool new feature in 2.7.0! Much appreciated 👍
